services:
  neo4j:
    image: neo4j:5.16-community
    restart: on-failure
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 3s
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: $NEO4J_USERNAME/$NEO4J_PASSWORD
  
  postgres:
    image: postgres:16.2
    restart: on-failure
    healthcheck:
      test: wget http://localhost:5432 || exit 1
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 3s
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER,
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD,
      POSTGRES_DB: $POSTGRES_DB
  
  api:
    build: .
    restart: on-failure
    depends_on:
      neo4j:
        condition: service_healthy
    ports: 
      - "8080:80"

  client:
    image: ghcr.io/organizationmercury/mercury-client:develop
    restart: on-failure
    ports:
      - "4200:80"
  