name: publish

on: 
  push:
    branches: [ master, develop ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup .net
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: 7.0.x

      - name: restore
        run: dotnet restore ./Mercury.sln
      
      - name: build
        run: dotnet build ./Mercury.sln --configuration Release --no-restore

      - name: tests
        run: dotnet test ./Mercury.sln --configuration Release --no-build

      - name: publish
        run: dotnet publish ./Mercury.sln --configuration Release --no-build

  publish-image:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
       
      - name: login to docker hub
        uses: docker/login-action@v3
        with: 	     
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.AUTH_TOKEN }}

      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: mercury-api${{ github.ref_name == 'develop' && '-dev' || '' }} 
